<?xml version="1.0" ?>
<testsuite errors="0" failures="0" name="TestDB-20181102144059" tests="22" time="4.405">
	<testcase classname="TestDB" name="test_create_allocation_invalid" time="0.291"/>
	<testcase classname="TestDB" name="test_create_allocation_valid" time="0.207"/>
	<testcase classname="TestDB" name="test_create_empty_group_exist" time="0.188"/>
	<testcase classname="TestDB" name="test_create_empty_group_notexist" time="0.187"/>
	<testcase classname="TestDB" name="test_create_group_with_members" time="0.202"/>
	<testcase classname="TestDB" name="test_create_item" time="0.226"/>
	<testcase classname="TestDB" name="test_create_order" time="0.188"/>
	<testcase classname="TestDB" name="test_create_receipt" time="0.195"/>
	<testcase classname="TestDB" name="test_delete_allocation" time="0.213"/>
	<testcase classname="TestDB" name="test_delete_group" time="0.201"/>
	<testcase classname="TestDB" name="test_delete_item" time="0.195"/>
	<testcase classname="TestDB" name="test_delete_order" time="0.190"/>
	<testcase classname="TestDB" name="test_delete_receipt" time="0.198"/>
	<testcase classname="TestDB" name="test_login_exist" time="0.172"/>
	<testcase classname="TestDB" name="test_login_notexist" time="0.172"/>
	<testcase classname="TestDB" name="test_modify_allocation_invalid" time="0.204"/>
	<testcase classname="TestDB" name="test_modify_allocation_valid" time="0.214"/>
	<testcase classname="TestDB" name="test_modify_item_amount" time="0.204"/>
	<testcase classname="TestDB" name="test_modify_item_name" time="0.206"/>
	<testcase classname="TestDB" name="test_remove_members_from_group" time="0.200"/>
	<testcase classname="TestDB" name="test_sign_up_exist" time="0.176"/>
	<testcase classname="TestDB" name="test_sign_up_notexist" time="0.176"/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py:329: Warning: (1008, "Can't drop database 'TESTTEST'; database doesn't exist")
  self._do_get_result()
]]>	</system-err>
</testsuite>
